### PR TITLE
make it upload the client to the workflow, for archival.

### PR DESCRIPTION
**Pull request by chicken-nugget1104**
does what the title is, super useful for archiving old builds.

we need this man

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
@GoldenretriverYT

**Comment by retrievaaaa** [comment]
pretty sure artifacts are only stored for a limited amount of time

**Comment by chicken-nugget1104** [comment]
> pretty sure artifacts are only stored for a limited amount of time

no they are permanent from what i know, unless you want me to make it so uh it uploads a release instead, but that would be extra work (more secrets n stuff) but we can try, if it doesn't work i can do release's, but please do merge, would be neat.

@GoldenretriverYT

**Comment by retrievaaaa** [comment]
https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization its limited yeah, would be great if you would make it use releases instead, or we could upload it to archive.org automatically

**Comment by chicken-nugget1104** [comment]
> https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization its limited yeah, would be great if you would make it use releases instead, or we could upload it to archive.org automatically

let's do the second approach if we can. release's are stress.

@GoldenretriverYT

**Comment by retrievaaaa** [comment]
alr

**Comment by chicken-nugget1104** [comment]
> alr

gonna do it for both the beta branch and release branch, or if you want to do it yourself you can. @GoldenretriverYT

**Comment by retrievaaaa** [comment]
just did

**Comment by retrievaaaa** [comment]
hold on gotta add to beta aswell

**Comment by retrievaaaa** [comment]
thx for your contribution :)

**Pull request merged**
